#-------------------------------
# Site Settings
title: Prospect Keyboards 
logo: '/images/logo1_v2.png'
author: Ben Shapiro
description: Built in Oakley, UT.


#-------------------------------
# Menu Settings ------ NEED MENU - HERE IS IT
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'


#-------------------------------
# Hero Settings
hero:
#   hero__title: Prospect Systems
#   hero__description: I create keyboards that are delightful to use and uniquely tailored to your needs and wants. I will help you achieve the sound, feel and aesthetic you have in mind. I also sell keyboards that I have built that I have deemed of high quality and general appeal (these for now will be sold through Ebay). If you are interested, <a href="mailto:prospectkeys@gmail.com">shoot me an email</a> or <a href="https://www.ebay.com/usr/bsh339">browse what I have available on Ebay</a>.
  
  
#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: I will work with you and my maker partners to build you a unique, highly customized, luxury keyboard. I stream the whole process on Twitch. Also let me know if you have the parts and would like me to assemble it on stream. Feel free to browse some of my past commissions:
  portfolio__gallery:

    - image: /images/DSC00073.JPG
      title: Green Tofu with Green Tea
      description: Dark Green Tofu, Geekark Tea PBT Keycaps, Boba U4T, Polycarb Plate
      
#     - image: /images/DSC00068.JPG
#       title: Bakanekko60 with 
#       description: Dark Green Tofu, Geekark Tea PBT Keycaps, Boba U4T, Polycarb Plate

    - image: /images/103.jpg
      title: Tofu HHKB
      description: Tofu HHKB with Gateron Yellow, and EPBT Grand Tour

    - image: /images/102.jpg
      title: Prime_E Keyboard
      description: Prime_E from Prime Keyboards, with Boba U4T and EPBT Grand Tour
      

    - image: /images/32.jpg
      title: <a href="http://prospectkeys.com/frankenboard/">Wood Frankenboard</a>
      description: WT60-D WEIRDFLEX PCB, Mode Designs Signal Tactile Switches, KbdFans PolyCarb Plate, Wood 60% Modded GH-64 Case
           

    - image: /images/29.jpg
      title: 60% Resin Build
      description: Durock T1s lubed with Krytox 205g0, Alopow Black Resin 60% Case, Maxkeys High Profile SA ABS Doubleshot Keycaps, GZ60 PCB Solder Version
    
      


    # - image: /images/56.jpg
    #   title: 
    #   description:
      
    # - image: /images/46.jpg
    #   title: 
    #   description:
      
      
    # - image: /images/47.jpg
    #   title: 
    #   description:


    - image: /images/48.jpg
      title: Gingham With T1
      description: Gingham Through Hole Keyboard, Durock T1, PBT Keycaps, Tape mod
      

    - image: /images/53.jpg
      title: Custom CM RapidFire 
      description: Yellow Switches with 205g0
   
      

      

     


#     - image: /images/16.jpg
#       title: GEEEK DIY Build
#       description: Alpenfohn Black Ridge, Mini ITX, GEEEK A30


#     - image: /images/keyb1.jpg
#       title: Modded Drop CTRL
#       description: by Benjamin Shapiro
      
    # - image: /images/gallery-05.jpg
    #   title: Luca Bravo
    #   description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    # - image: /images/gallery-06.jpg
    #   title: Isaac Benhesed
    #   description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    # - image: /images/gallery-07.jpg
    #   title: Water Journal
    #   description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    # - image: /images/gallery-08.jpg
    #   title: Luca Bravo
    #   description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    # - image: /images/gallery-09.jpg
    #   title: Books and Laptop
    #   description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates about new products and services # Add your Title
  mailchimp__identifier: 606ca5da81
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
# - {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
# - {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
# - {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-youtube", color: "#e4405f", label: YouTube, link: "https://www.youtube.com/channel/UCuAfxUzRGuxvV2m--i_Sigg"}
- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
# - {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: prospectkey@gmail.com # Add your email for contact form
  description: Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.
